#!/bin/bash
#SBATCH -J tdlamdaxteps
#SBATCH -o /sphere/mattar-lab/mousemazemodeling/MouseMaze/TDlambdaXsteps_stan/slurm.out
#SBATCH -p general_gpu_k80

# NOTE!! Need to create a virtual env on ssrde with all the requirements installed
source /home/AD/usingla/mvenv/bin/activate

export PREFIX=TDlambdaXsteps_   # prefix for stan model file, log files, data directories etc
ROOT=../${PREFIX}stan
export STAN_FILE=${ROOT}/${PREFIX}.stan       # stan model file

export INIT=RAND  # Initial state values, Options available: ZERO, RAND, ONES
export PARAMS=alpha,beta,gamma,lamda  # List of free parameters in model
export UPPER_BOUNDS=[1,10,1,1]  # Set upper bounds for all parameters

LOG_DIR=${ROOT}/logs/${PREFIX}
mkdir -p ${LOG_DIR}
d=`date +%s`

export RESULTS_DIR=${ROOT}/stan_results/${PREFIX}
echo $STAN_FILE $RESULTS_DIR

echo Starting python using $1 as input
LOG_FILE=${LOG_DIR}/log-${d}.log
echo "Log File: "${LOG_FILE}
python -u $1 2>&1 | tee ${LOG_FILE}
exitcode=$?
echo "Exited with code: "$exitcode
